project_id = "mwohaji"

[functions.ingest-tour-data]
verify_jwt = false

[functions.generate-plan-explanation]
verify_jwt = true

[functions.ingest-store-data]
verify_jwt = false

[functions.ingest-naver-places]
verify_jwt = false
